### ISSUE TITLE
AssertionError: Caught AssertionError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by saba99** [yuangan/EAT_code#21]
CustomDatasetDataLoader
dataset [FaceDataset] was created
1it [00:02,  2.94s/it]==================done=====================
2it [00:06,  3.37s/it]==================done=====================
2it [00:06,  3.31s/it]
Traceback (most recent call last):
  File "/content/drive/MyDrive/EAT_code/preprocess/vid2vid/data_preprocess.py", line 26, in <module>
==================done=====================
    for i, data in tqdm(enumerate(dataset)):
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 457, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/MyDrive/EAT_code/preprocess/vid2vid/data/face_preprocess_eat.py", line 36, in __getitem__
    assert(0)
AssertionError

**Comment by G-force78** [comment]
Thats intentional I believe. Check the demo/video_processed directory for your processed video. You will probably need to use the deepspeech_features.py from mozillas repo as its up to date. Then when you run the demo check you have cropped images in the name of your new processed video. Also check all the paths are correct as this was written for the developers own environment.

**Comment by yuangan** [comment]
Thank you for your attention. If the results are right, don't worry. I just stopped [here](https://github.com/yuangan/EAT_code/blob/main/preprocess/vid2vid/data/face_preprocess_eat.py#L35) for convenience.
